- name: To understand the variables in Ansible
  hosts: local
  connection: local
  vars:
    NAME: Reshwanth
    COURSE: Devops
    WHEN: soon
  tasks:
    - name: To print the variable names
      ansible.builtin.debug:
        msg: "This is {{NAME}}, I am learning {{COURSE}}, I will complete and get a job {{WHEN}}"
