- name: To pull the variables from other yaml file
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: I pulled the variables from course.yaml
      ansible.builtin.debug:
        msg: "This is {{NAME}}, and I am learning {{COURSE}} and soon I will get {{PURPOSE}}"
