- name: To write variables in inventory
  hosts: local
  connection: local
  tasks:
    - name: Reading variables from inventory
      ansible.builtin.debug:
      msg: "I am practicing {{Practice} for {{Duration}}"
