- name: loops
  hosts: local
  tasks:
    - name: to understand loops
      ansible.builtin.debug:
        msg: "Printing{ { item } }"
      loop:
        - "Reshwanth"
        - "harini"
        - "Suresh"