- name: To install all packages
  hosts: local
  connection: local
  tasks:
    - name: Installing the packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{item.state}}"
      loop:
        - { name: "git", state: "present" }
        - { name: "nginx", state: "present" }
        - { name: "gcc", state: "present" }
