[web]
98.84.187.166 Course="AWS" Trainer="ShivaKumar" Duration="120HRS"
localhost Course="Azure" Trainer="ShivaKumar" Duration="10HRS"

[local]
localhost
[local:vars]  
Course="Devops"
Trainer="ShivaKumar"
Duration="120HRS"